include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}

queues {
  "task-queue-dev" {
    defaultVisibilityTimeout = 30
    deadLettersQueue {
      name = "task-dlq-dev"
      maxReceiveCount = 3
    }
  }
  "task-dlq-dev" {}
}
